---
version: 2.1
description: "To upload your iOS/Android application to DeployGate. \nDeployGate enable
  to share in-development apps with others instantly. \nFor more detail, please read
  references in [DeployGate.com](https://deploygate.com/?locale=en)\n"
examples:
  upload-app-step:
    description: You can upload apps with embedding into the current your job
    usage:
      orbs:
        deploygate: jmatsu-sandbox/deploygate-upload-app@dev:first
      version: 2.1
      jobs:
        build:
          docker:
          - image: circleci/android:api-28-alpha
          steps:
          - checkout
          - run: "./gradlew assembleDebug"
          - deploygate/upload-app:
              api_key: "$DG_API_TOKEN"
              owner_name: "$DG_APP_OWNER"
              app_path: app/build/outputs/apk/debug/app-debug.apk
              visibility: public
      workflows:
        deployment:
          jobs:
          - build
  upload-app-workflow:
    description: You can upload apps with pre/post steps
    usage:
      orbs:
        deploygate: jmatsu-sandbox/deploygate-upload-app@dev:first
      version: 2.1
      workflows:
        deployment:
          jobs:
          - deploygate/upload-app-job:
              api_key: "$DG_API_TOKEN"
              owner_name: "$DG_APP_OWNER"
              app_path: app/build/outputs/apk/debug/app-debug.apk
              visibility: public
              pre-upload-app-steps:
              - checkout
              - run: "./gradlew assembleDebug"
commands:
  upload-app:
    parameters:
      version:
        type: string
        default: 0.0.1
      api_key:
        type: string
        description: The authorization token to be used when uploading app
      owner_name:
        type: string
        description: The owner name of this application
      app_path:
        type: string
        description: App's binary file (IPA/APK) to be uploaded. Cannot use '~' for
          now so please use $HOME instead
      visibility:
        type: enum
        default: private
        enum:
        - private
        - public
        description: |
          For newly uploaded apps only, specify the app's name and icon privacy settings to either private or public.
          This is just only for visibility on your apps list in profile page, not for allowing download or install by anonymous.
          Download or install apps is allowd only your app's member or invitee who knows your generated public link.
          By default, Personal Free Plans are set to public, and all other plans are set to private.
          This setting does not apply for updates, and any changes made will be ignored.
      message:
        type: string
        default: ''
        description: A short message to explain this version
      distribution_key:
        type: string
        default: ''
        description: |
          By specifying the distribution page's hash, that distribution page will be updated simultaneously.
          The "xxxx" portion of the distributed page's URL like https://deploygate.com/distributions/xxxx
      distribution_name:
        type: string
        default: ''
        description: "Specify the name of the updated distribution page. \nIf none
          exists, a new distribution page will be created. \nPossible uses include
          creating distribution pages for each Git branch name.\n"
      release_note:
        type: string
        default: ''
        description: Message displayed during distribution page app updates
      disable_notify:
        type: boolean
        default: false
        description: "(iOS only) A setting of true disables Push notification emails."
    steps:
    - run:
        name: Distribute your app to DeployGate
        command: |
          export api_key="<<parameters.api_key>>"
          export owner_name="<<parameters.owner_name>>"
          export app_path="<<parameters.app_path>>"
          export visibility="<<parameters.visibility>>"
          export message="<<parameters.message>>"
          export distribution_key="<<parameters.distribution_key>>"
          export distribution_name="<<parameters.distribution_name>>"
          export release_note="<<parameters.release_note>>"
          export disable_notify="<<parameters.disable_notify>>"

          curl -sL "https://raw.githubusercontent.com/jmatsu/deploygate-orbs/upload-app-<<parameters.version>>/upload-app/upload-step.bash" | bash
jobs:
  upload-app-job:
    parameters:
      version:
        type: string
        default: 0.0.1
      api_key:
        type: string
        description: The authorization token to be used when uploading app
      owner_name:
        type: string
        description: The owner name of this application
      app_path:
        type: string
        description: App's binary file (IPA/APK) to be uploaded. Cannot use '~' for
          now so please use $HOME instead
      visibility:
        type: enum
        default: private
        enum:
        - private
        - public
        description: |
          For newly uploaded apps only, specify the app's name and icon privacy settings to either private or public.
          This is just only for visibility on your apps list in profile page, not for allowing download or install by anonymous.
          Download or install apps is allowd only your app's member or invitee who knows your generated public link.
          By default, Personal Free Plans are set to public, and all other plans are set to private.
          This setting does not apply for updates, and any changes made will be ignored.
      message:
        type: string
        default: ''
        description: A short message to explain this version
      distribution_key:
        type: string
        default: ''
        description: |
          By specifying the distribution page's hash, that distribution page will be updated simultaneously.
          The "xxxx" portion of the distributed page's URL like https://deploygate.com/distributions/xxxx
      distribution_name:
        type: string
        default: ''
        description: "Specify the name of the updated distribution page. \nIf none
          exists, a new distribution page will be created. \nPossible uses include
          creating distribution pages for each Git branch name.\n"
      release_note:
        type: string
        default: ''
        description: Message displayed during distribution page app updates
      disable_notify:
        type: boolean
        default: false
        description: "(iOS only) A setting of true disables Push notification emails."
      executor-name:
        type: executor
        default: default
      pre-upload-app-steps:
        type: steps
        default: []
      post-upload-app-steps:
        type: steps
        default: []
    executor: "<< parameters.executor-name >>"
    steps:
    - steps: "<< parameters.pre-upload-app-steps >>"
    - upload-app:
        api_key: "<< parameters.api_key >>"
        owner_name: "<< parameters.owner_name >>"
        app_path: "<< parameters.app_path >>"
        visibility: "<< parameters.visibility >>"
        message: "<< parameters.message >>"
        distribution_key: "<< parameters.distribution_key >>"
        distribution_name: "<< parameters.distribution_name >>"
        release_note: "<< parameters.release_note >>"
        disable_notify: "<< parameters.disable_notify >>"
    - steps: "<< parameters.post-upload-app-steps >>"
executors:
  default:
    docker:
    - image: circleci/android:api-28-alpha
